@extends('inner.layouts.main')
@section('title', 'All Payment Links')
@section('user-payment-link', 'active')
@section('user-need-wallet', 'locked')
@section('content')

    <div class="table container">
        <h4>Payment Links (Generated by me)</h4>
        <table>
            <thead>
                <tr>
                    <th>Link</th>
                    <th>Amount</th>
                    <th>Account number</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Paid on</th>
                </tr>
            </thead>
            <tbody>
                @if(count($links) > 0)
                @foreach ($links as $link)
                <tr>
                    <td>{{$link->link}}</td>
                    <td>{{format_number($link->amount)}}</td>
                    <td>{{$link->account_number}}</td>
                    <td>{{$link->email}}</td>
                    <td>
                        @if($link->status == 1)
                            <button class="btn primary sm">Paid</button>
                        @else
                            <button class="btn danger sm">Unpaid</button>
                        @endif
                    </td>
                    <td>{{$link->payment_on ?? '---'}}</td>

                </tr>   
                @endforeach
                @else
                    <tr>
                        <td colspan="6"> No data added.</td>
                    </tr>
                @endif
            </tbody>
        </table>
        <div class="pagination">
            {{ $links->links('vendor.pagination.custom') }} 
        </div>
        <h4>Payment Links (For me)</h4>
        <table>
            <thead>
                <tr>
                    <th>Link</th>
                    <th>Amount</th>
                    <th>Requested By</th>
                    <th>Payment on</th>
                </tr>
            </thead>
            <tbody>
                @if(count($forMeLinks) > 0)
                @foreach ($forMeLinks as $link)
                <tr>
                    <td>
                        @if($link->status == 0)
                        <a href="{{url('main/user/funds/pay-via-link')}}/{{$link->link}}" class="btn primary sm">Pay</a>
                    @else
                        <button class="btn warning sm">Alread Paid</button>
                    @endif
                    </td>
                    <td>{{format_number($link->amount)}}</td>
                    <td>{{$link->email}}</td>
                    <td>{{$link->payment_on ?? '---'}}</td>

                </tr>   
                @endforeach
                @else
                    <tr>
                        <td colspan="4"> No data added.</td>
                    </tr>
                @endif
            </tbody>
        </table>
        <div class="pagination">
            {{ $forMeLinks->links('vendor.pagination.custom') }} 
        </div>
    </div>
   

    @if (session('success'))
    <div class="toastr success">
      {{ session('success') }}
    </div>
  @endif
  
  @if (session('error'))
    <div class="toastr error">
      {{ session('error') }}
    </div>
  @endif
@endsection