@extends('inner.layouts.main')
@section('title', 'All Payment Links')
@section('user-payment-link', 'active')
@section('user-need-wallet', 'locked')
@section('content')

<div class="table container">
    <h4>Payment Links (Generated by me)</h4>
    <table>
        <thead>
            <tr>
                <th>Link</th>
                <th>Amount</th>
                <th>Account number</th>
                <th>Email</th>
                <th>QR</th>
                <th>Status</th>
                <th>Paid on</th>
            </tr>
        </thead>
        <tbody>
            @if(count($links) > 0)
            @foreach ($links as $link)
            <tr>
                <td>{{$link->link}}</td>
                <td>{{format_number($link->amount)}}</td>
                <td>{{$link->account_number}}</td>
                <td>{{$link->email}}</td>
                <td>
                    @if($link->status == 0)
                    <button class="btn primary sm showQr" data-link="{{url('main/user/funds/pay-via-link')}}/{{$link->link}}">Show QR</button>
                    @endif
                </td>
                <td>
                    @if($link->status == 1)
                        <button class="btn primary sm">Paid</button>
                    @else
                        <button class="btn danger sm">Unpaid</button>
                    @endif
                </td>
                <td>{{$link->payment_on ?? '---'}}</td>
            </tr>   
            @endforeach
            @else
                <tr>
                    <td colspan="6"> No data added.</td>
                </tr>
            @endif
        </tbody>
    </table>
    <div class="pagination">
        {{ $links->links('vendor.pagination.custom') }} 
    </div>

    <h4>Payment Links (For me)</h4>
    <table>
        <thead>
            <tr>
                <th>Link</th>
                <th>QR</th>
                <th>Amount</th>
                <th>Requested By</th>
                <th>Payment on</th>
            </tr>
        </thead>
        <tbody>
            @if(count($forMeLinks) > 0)
            @foreach ($forMeLinks as $link)
            <tr>
                <td>
                    @if($link->status == 0)
                    <a href="{{url('main/user/funds/pay-via-link')}}/{{$link->link}}" class="btn primary sm">Pay</a>
                    @else
                        <button class="btn warning sm">Already Paid</button>
                    @endif
                </td>
                <td>
                    @if($link->status == 0)
                    <button class="btn primary sm showQr" data-link="{{url('main/user/funds/pay-via-link')}}/{{$link->link}}">Show QR</button>
                    @endif
                </td>
                <td>{{format_number($link->amount)}}</td>
                <td>{{$link->email}}</td>
                <td>{{$link->payment_on ?? '---'}}</td>
            </tr>   
            @endforeach
            @else
                <tr>
                    <td colspan="4"> No data added.</td>
                </tr>
            @endif
        </tbody>
    </table>
    <div class="pagination">
        {{ $forMeLinks->links('vendor.pagination.custom') }} 
    </div>
</div>

<div class="qr-code-wrapper" style="display: none;">
    <div class="qr-code-content">
        <header>
            <h1>QR Code</h1>
            <p>Generated QR Code for Payment Link</p>
        </header>
        <div class="qr-code">
            <img src="" alt="QR Code" class="qr-image"> <!-- Add a class for easier selection -->
        </div>
        <button class="btn primary sm downloadQr">Download QR Code</button>
        <div class="share-buttons">
            <button class="btn primary sm shareFacebook" title="Share on Facebook">
                <i class="fab fa-facebook-f"></i>
            </button>
            <button class="btn primary sm shareTwitter" title="Share on Twitter">
                <i class="fab fa-twitter"></i>
            </button>
            <button class="btn primary sm shareWhatsApp" title="Share on WhatsApp">
                <i class="fab fa-whatsapp"></i>
            </button>
        </div>
        <button class="btn danger sm closeQr">Close</button>
    </div>
</div>


@if (session('success'))
<div class="toastr success">
  {{ session('success') }}
</div>
@endif

@if (session('error'))
<div class="toastr error">
  {{ session('error') }}
</div>
@endif

@endsection
